### ISSUE TITLE
Difficulty getting to work

### ISSUE THREAD

**Issue by camjac251** [ejlungay/Send-Mouse-Event-to-Virtualbox-using-Python#1]
I've been looking for a way to send a mouse movement every few minutes in Virtualbox without affecting the host machine's mouse and this seems like it. I can't seem to get it to work sadly though. I'm using Anaconda with python 3.7 on Windows 10, My VM is Android-x86, which has a software mouse that works in Virtualbox. I disabled the mouse integration at first so my cursor would be exclusive to Virtualbox if I clicked inside the window, but I recently changed the mouse from tablet to ps2 mouse in options.

Update: I switched from the ps2 to usb tablet input for the mouse and it seems to move the mouse with mouse integration turned on. If I turn off mouse integration which forces the mouse to not leave the window borders when you click in the windows, and if I hit right control to release the mouse and run the script, it seems to fail.

**Comment by camjac251** [comment]
I'm trying to control an app on Android-x86 that requires mouse integration turned off to move the mouse in this app, but doing so causes the sdk to not move the mouse.

**Comment by noobfromph** [comment]
hi @camjac251 this is working with python2

**Comment by camjac251** [comment]
I ended up moving to a different package, but haven't used it in quite a while. It was in an anaconda environment too activated by my cmd script. This was in Python 3.

```py
from vboxapi import VirtualBoxManager
from random import randint
import sys
import time
from datetime import datetime, timedelta


mgr = VirtualBoxManager(None, None)

vbox = mgr.getVirtualBox()
machine = vbox.findMachine('VirtualBox')
session = mgr.getSessionObject(vbox)

machine.LockMachine(session, mgr.constants.LockType_Shared)

def mouseloop():
	print("Moving mouse")
	end_time = datetime.now() + timedelta(seconds=3)
	while datetime.now() < end_time:
		print("mouse movement")
		try:
			session.Console.Mouse.putMouseEvent(randint(-1,1),randint(-1,1),0,0,0)
		except KeyboardInterrupt:
			print ("macro stopped")
			sys.exit()

def update():
	while True:
		timeout = randint(180,420)
		print("Waiting", timeout, "seconds")
		time.sleep(timeout)
		mouseloop()
update()
```

```cmd
:: Run a command inside the %pyenv% conda environment and exit
:: Because 'conda run' is a lie

SET interactive=0
SET pyenv=vbox

CALL "C:\Users\User\anaconda3\Scripts\activate.bat" activate "%pyenv%"

:: Run whatever command line we were passed
CALL python C:\Users\User\Documents\vbox-scripts\sendMouseCoordinates.py
SET ret=%ERRORLEVEL%
CALL conda deactivate

IF "%interactive%"=="0" PAUSE
EXIT /B %ret%
```
